{ lib, pkgs, config, ... }:

let
  cfg = config.services.pdnsStack;

  listToCSV = list:
    if builtins.isNull list || list == [] then ""
    else lib.concatStringsSep "," list;
in
{
  options.services.pdnsStack = {
    enable = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = ''
        Enable the PowerDNS stack (dnsdist + two authoritative instances + recursor + PowerDNS-Admin + MariaDB)
        packaged as a Docker Compose deployment.
      '';
    };

    directory = lib.mkOption {
      type = lib.types.str;
      default = "/etc/pdns-stack";
      description = "Directory where docker-compose and supporting files are rendered.";
    };

    routerIPs = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [ "192.168.2.1" "192.168.3.1" ];
      description = "Router IPs that dnsdist should bind to (one per interface / network).";
    };

    upstreamResolvers = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [ "9.9.9.9" "1.1.1.1" ];
      description = "Upstream recursive resolvers the recursor should forward to.";
    };

    mariadbRootPassword = lib.mkOption {
      type = lib.types.str;
      default = "changeme_root_pw";
      description = "MariaDB root password. Replace in production.";
    };

    pdnsDbPassword = lib.mkOption {
      type = lib.types.str;
      default = "pdns-password";
      description = "Password for the PowerDNS MariaDB user. Replace in production.";
    };

    pdnsApiKeyHomelab = lib.mkOption {
      type = lib.types.str;
      default = "auth-homelab-key";
      description = "API key for the HOMELAB authoritative PowerDNS instance.";
    };

    pdnsApiKeyLan = lib.mkOption {
      type = lib.types.str;
      default = "auth-lan-key";
      description = "API key for the LAN authoritative PowerDNS instance.";
    };

    powerdnsAdminSecret = lib.mkOption {
      type = lib.types.str;
      default = "powerdns-admin-secret";
      description = "SECRET_KEY for the PowerDNS-Admin web UI.";
    };
  };

  config = lib.mkIf cfg.enable {
    virtualisation.docker.enable = true;

    environment.systemPackages = lib.mkAfter [
      pkgs.docker
      pkgs.docker-compose
      pkgs.curl
    ];

    environment.etc."pdns-stack/docker-compose.yml".text =
      lib.concatStringsSep "\n" [
        "# Generated by services.pdnsStack NixOS module"
        ""
        "version: \"3.8\""
        "services:"
        "  mariadb:"
        "    image: mariadb:12"
        "    restart: unless-stopped"
        "    environment:"
        "      MYSQL_ROOT_PASSWORD: \"${cfg.mariadbRootPassword}\""
        "      MYSQL_DATABASE: powerdns"
        "      MYSQL_USER: pdns"
        "      MYSQL_PASSWORD: \"${cfg.pdnsDbPassword}\""
        "    volumes:"
        "      - mariadb-data:/var/lib/mysql"
        "    networks:"
        "      pdns-net:"
        "        ipv4_address: 172.28.0.20"
        ""
        "  pdns-auth-homelab:"
        "    image: powerdns/pdns-auth-51:latest"
        "    environment:"
        "      - PDNS_API=yes"
        "      - PDNS_API_KEY=${cfg.pdnsApiKeyHomelab}"
        "      - PDNS_LAUNCH=gmysql"
        "      - PDNS_GMYSQL_HOST=172.28.0.20"
        "      - PDNS_GMYSQL_user=pdns"
        "      - PDNS_GMYSQL_password=${cfg.pdnsDbPassword}"
        "      - PDNS_GMYSQL_dbname=powerdns"
        "      - PDNS_WEBSERVER=yes"
        "      - PDNS_WEBSERVER_ADDRESS=0.0.0.0"
        "      - PDNS_WEBSERVER_PORT=8081"
        "    networks:"
        "      pdns-net:"
        "        ipv4_address: 172.28.0.11"
        ""
        "  pdns-auth-lan:"
        "    image: powerdns/pdns-auth-51:latest"
        "    environment:"
        "      - PDNS_API=yes"
        "      - PDNS_API_KEY=${cfg.pdnsApiKeyLan}"
        "      - PDNS_LAUNCH=gmysql"
        "      - PDNS_GMYSQL_HOST=172.28.0.20"
        "      - PDNS_GMYSQL_user=pdns"
        "      - PDNS_GMYSQL_password=${cfg.pdnsDbPassword}"
        "      - PDNS_GMYSQL_dbname=powerdns"
        "      - PDNS_WEBSERVER=yes"
        "      - PDNS_WEBSERVER_ADDRESS=0.0.0.0"
        "      - PDNS_WEBSERVER_PORT=8082"
        "    networks:"
        "      pdns-net:"
        "        ipv4_address: 172.28.0.12"
        ""
        "  pdns-recursor:"
        "    image: powerdns/pdns-recursor-54:latest"
        "    environment:"
        "      - RECURSOR_LOCAL_ADDRESS=172.28.0.13"
        "      - RECURSOR_LOCAL_PORT=5300"
        "      - RECURSOR_FORWARD_ZONES_RECURSE=.=${listToCSV cfg.upstreamResolvers}"
        "    networks:"
        "      pdns-net:"
        "        ipv4_address: 172.28.0.13"
        ""
        "  redis:"
        "    image: redis:8"
        "    networks:"
        "      pdns-net:"
        "        ipv4_address: 172.28.0.15"
        ""
        "  powerdns-admin:"
        "    image: ngoduykhanh/powerdns-admin:latest"
        "    ports:"
        "      - 8080:80"
        "    depends_on:"
        "      - mariadb"
        "    environment:"
        "      - ADMIN_EMAIL=admin@example.local"
        "      - SECRET_KEY=${cfg.powerdnsAdminSecret}"
        "      - SQLA_DB_USER=pdns"
        "      - SQLA_DB_PASSWORD=${cfg.pdnsDbPassword}"
        "      - SQLA_DB_HOST=172.28.0.20"
        "      - SQLA_DB_NAME=powerdns_admin"
        "      - REDIS_URL=redis://redis:6379/0"
        "      - PDNS_API_URL=http://172.28.0.11:8081"
        "      - PDNS_API_KEY=${cfg.pdnsApiKeyHomelab}"
        "    networks:"
        "      pdns-net:"
        "        ipv4_address: 172.28.0.14"
        ""
        "  dnsdist:"
        "    image: powerdns/dnsdist-21:latest"
        "    network_mode: host"
        "    volumes:"
        "      - ./dnsdist/dnsdist.lua:/etc/dnsdist/dnsdist.lua:ro"
        "    restart: unless-stopped"
        ""
        "networks:"
        "  pdns-net:"
        "    driver: bridge"
        "    ipam:"
        "      config:"
        "        - subnet: 172.28.0.0/24"
        ""
        "volumes:"
        "  mariadb-data: {}"
      ];

    environment.etc."pdns-stack/dnsdist/dnsdist.lua".text =
      lib.concatStringsSep "\n" (
        [
          "-- dnsdist.lua generated by services.pdnsStack"
          ""
        ]
        ++ (map (ip: "addLocal('" + ip + ":53')") cfg.routerIPs)
        ++ [
          ""
          "recursor = newServer({address='172.28.0.13', port=5300, name='recursor'})"
          "auth_homelab = newServer({address='172.28.0.11', port=53, name='pdns-auth-homelab'})"
          "auth_lan     = newServer({address='172.28.0.12', port=53, name='pdns-auth-lan'})"
          ""
          "addPoolRule('recursorPool', {recursor})"
          "addPoolRule('authHomelabPool', {auth_homelab})"
          "addPoolRule('authLanPool', {auth_lan})"
          ""
          "homelabNet = newNetmask('192.168.2.0/24')"
          "lanNet     = newNetmask('192.168.3.0/24')"
          ""
          "function localRule(dq)"
          "  local q = dq.qname:toString():lower()"
          "  if q:match('%.jeandr%.net%.$') or q == 'jeandr.net.' then"
          "    if homelabNet:contains(dq.remoteaddr) then return pool.get('authHomelabPool') end"
          "    if lanNet:contains(dq.remoteaddr) then return pool.get('authLanPool') end"
          "    return pool.get('recursorPool')"
          "  end"
          "  return pool.get('recursorPool')"
          "end"
          ""
          "addAction(AllRule(), LuaAction(localRule))"
          "setVerbose(true)"
        ]
      );

    environment.etc."pdns-stack/manage.sh" = {
      text = ''
        #!/bin/sh
        exec ${pkgs.docker}/bin/docker compose -f ${cfg.directory}/docker-compose.yml "$@"
      '';
      mode = "0755";
    };

    systemd.services.pdns-stack = {
      description = "PowerDNS docker-compose stack";
      after = [ "network-online.target" "docker.service" ];
      wants = [ "network-online.target" "docker.service" ];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
        ExecStart = "${pkgs.docker}/bin/docker compose -f ${cfg.directory}/docker-compose.yml up -d";
        ExecStop = "${pkgs.docker}/bin/docker compose -f ${cfg.directory}/docker-compose.yml down";
        TimeoutStartSec = "120s";
        TimeoutStopSec = "120s";
      };
      wantedBy = [ "multi-user.target" ];
    };
  };
}


