# Router configuration variables
# This file is generated by the installation script

{
  # System settings
  hostname = "nixos-router";
  timezone = "America/Anchorage";
  username = "routeradmin";

  # WAN configuration
  wan = {
    type = "dhcp";  # "dhcp" or "pppoe"
    interface = "eno1";
  };

  # LAN configuration
  lan = {
    interfaces = [ "enp4s0" "enp5s0" "enp6s0" "enp7s0" ];  # Bridge interfaces
    ip = "192.168.4.1";
    prefix = 24;
  };

  # DHCP configuration
  dhcp = {
    start = "192.168.4.100";
    end = "192.168.4.200";
    leaseTime = "24h";
  };

  # Port Forwarding Rules
  portForwards = [
    {
      proto = "both";
      externalPort = 80;
      destination = "192.168.2.33";
      destinationPort = 80;
    }
    {
      proto = "both";
      externalPort = 443;
      destination = "192.168.2.33";
      destinationPort = 443;
    }
    {
      proto = "both";
      externalPort = 22000;
      destination = "192.168.2.33";
      destinationPort = 22000;
    }
    {
      proto = "both";
      externalPort = 4242;
      destination = "192.168.2.31";
      destinationPort = 4242;
    }
  ];

  # Dynamic DNS Configuration (optional)
  dyndns = {
    enable = false;  # Set to true to enable dynamic DNS updates
    provider = "linode";  # Currently only "linode" is supported
    
    # Domain and record to update
    domain = "example.com";
    subdomain = "";  # Leave empty for root domain, or specify subdomain like "router"
    
    # Linode API credentials (stored in sops secrets)
    # domainId and recordId can be found using: linode-cli domains list / linode-cli domains records-list DOMAIN_ID
    domainId = 0;  # Your Linode domain ID
    recordId = 0;  # Your Linode DNS record ID
    
    # Update interval when WAN IP hasn't changed
    checkInterval = "5m";  # How often to check for IP changes
  };

  # Defined Networking (Nebula VPN) Configuration (optional)
  dnclient = {
    enable = false;  # Set to true to enable Defined Networking
    
    # Enrollment code from https://admin.defined.net/
    # Can be removed after initial enrollment
    # For security, consider using enrollmentCodeFile with sops-nix instead
    enrollmentCode = "";  # Your enrollment code (optional, see docs)
    
    # Alternative: use a file for the enrollment code (recommended with sops-nix)
    # enrollmentCodeFile = "/run/secrets/dn-enrollment-code";  # Uncomment to use
    
    # Nebula port (UDP)
    port = 4242;  # Default Nebula port, change if needed
  };
}
