# Router configuration variables
# This file is generated by the installation script

{
  # System settings
  hostname = "nixos-router";
  timezone = "America/Anchorage";
  username = "routeradmin";
  
  # SSH authorized keys for the router admin user
  sshKeys = [
    # Add your SSH public keys here, one per line
    # Example: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJbG... user@hostname"
  ];

  # WAN configuration
  wan = {
    type = "dhcp";  # "dhcp" or "pppoe"
    interface = "eno1";
  };

  # LAN configuration - Multiple isolated networks
  lan = {
    # Physical port mapping (for reference):
    # enp4s0, enp5s0 = HOMELAB (left two ports on 4-port card)
    # enp6s0, enp7s0 = LAN (right two ports on 4-port card)
    
    bridges = [
      # HOMELAB network - servers, IoT devices
      {
        name = "br0";
        interfaces = [ "enp4s0" "enp5s0" ];
        ipv4 = {
          address = "192.168.2.1";
          prefixLength = 24;
        };
        ipv6.enable = false;
      }
      # LAN network - computers, phones, tablets
      {
        name = "br1";
        interfaces = [ "enp6s0" "enp7s0" ];
        ipv4 = {
          address = "192.168.3.1";
          prefixLength = 24;
        };
        ipv6.enable = false;
      }
    ];
    
    # Block traffic between HOMELAB and LAN at the router level
    # (Hera and Triton have dual NICs and can bridge as needed)
    isolation = true;
    
    # Exception: Allow specific LAN devices to access HOMELAB
    # Format: { source = "LAN IP"; sourceBridge = "br1"; destBridge = "br0"; }
    isolationExceptions = [
      {
        source = "192.168.3.50";  # Your workstation IP
        sourceBridge = "br1";      # LAN
        destBridge = "br0";        # HOMELAB
        description = "Workstation access to HOMELAB";
      }
    ];
  };

  # HOMELAB network configuration
  homelab = {
    # Network settings
    ipAddress = "192.168.2.1";
    subnet = "192.168.2.0/24";
    
    # DHCP settings
    dhcp = {
      start = "192.168.2.100";
      end = "192.168.2.200";
      leaseTime = "24h";
    };
    
    # DNS settings for this network
    dns = {
      # DNS A Records (hostname → IP address)
      a_records = {
        "homelab.local" = {
          ip = "192.168.2.33";
          comment = "Main homelab domain";
        };
        "router.homelab.local" = {
          ip = "192.168.2.1";
          comment = "Router address";
        };
        # Add more A records here:
        # "server.homelab.local" = { ip = "192.168.2.50"; comment = "Main server"; };
        # "nas.homelab.local" = { ip = "192.168.2.40"; comment = "NAS storage"; };
      };
      
      # DNS CNAME Records (alias → canonical name)
      cname_records = {
        "*.homelab.local" = {
          target = "homelab.local";
          comment = "Wildcard for all subdomains";
        };
        # Add more CNAME records here:
        # "www.homelab.local" = { target = "server.homelab.local"; comment = "Web server alias"; };
      };
      
      # Blocklist configuration
      blocklists = {
        enable = true;  # Master switch - set to false to disable all blocking
        
        stevenblack = {
          enable = true;
          url = "https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts";
          description = "Ads and malware blocking (250K+ domains)";
          updateInterval = "24h";  # Optional: defaults to 24h if not set
        };
        
        # Add more blocklists as needed:
        # oisd = {
        #   enable = false;
        #   url = "https://small.oisd.nl/domainswild";
        #   description = "Curated ads, tracking, and malware (100K+ domains)";
        # };
        # 
        # phishing-army = {
        #   enable = false;
        #   url = "https://phishing.army/download/phishing_army_blocklist.txt";
        #   description = "Phishing and scam protection";
        #   updateInterval = "12h";  # More frequent updates for security
        # };
      };
    };
  };
  
  # LAN network configuration
  lan = {
    # Network settings
    ipAddress = "192.168.3.1";
    subnet = "192.168.3.0/24";
    
    # DHCP settings
    dhcp = {
      start = "192.168.3.100";
      end = "192.168.3.200";
      leaseTime = "24h";
    };
    
    # DNS settings for this network
    dns = {
      # DNS A Records (hostname → IP address)
      a_records = {
        "lan.local" = {
          ip = "192.168.3.1";
          comment = "Main LAN domain";
        };
        "router.lan.local" = {
          ip = "192.168.3.1";
          comment = "Router address";
        };
        # Add more A records here:
        # "desktop.lan.local" = { ip = "192.168.3.50"; comment = "Desktop computer"; };
        # "laptop.lan.local" = { ip = "192.168.3.51"; comment = "Laptop"; };
      };
      
      # DNS CNAME Records (alias → canonical name)
      cname_records = {
        "*.lan.local" = {
          target = "lan.local";
          comment = "Wildcard for all subdomains";
        };
        # Add more CNAME records here:
        # "www.lan.local" = { target = "router.lan.local"; comment = "Web interface alias"; };
      };
      
      # Blocklist configuration
      blocklists = {
        enable = true;  # Master switch - set to false to disable all blocking
        
        stevenblack = {
          enable = true;
          url = "https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts";
          description = "Ads and malware blocking (250K+ domains)";
          # No updateInterval = defaults to 24h
        };
        
        # Add more blocklists as needed:
        # energized-blu = {
        #   enable = false;
        #   url = "https://block.energized.pro/blu/formats/hosts.txt";
        #   description = "Balanced blocking (200K+ domains)";
        #   updateInterval = "48h";
        # };
        # 
        # adaway = {
        #   enable = false;
        #   url = "https://adaway.org/hosts.txt";
        #   description = "Mobile-focused ad blocking";
        #   updateInterval = "1w";  # Weekly updates
        # };
      };
    };
  };

  # Port Forwarding Rules
  portForwards = [
    {
      proto = "both";
      externalPort = 80;
      destination = "192.168.2.33";
      destinationPort = 80;
    }
    {
      proto = "both";
      externalPort = 443;
      destination = "192.168.2.33";
      destinationPort = 443;
    }
    {
      proto = "both";
      externalPort = 22000;
      destination = "192.168.2.33";
      destinationPort = 22000;
    }
    {
      proto = "both";
      externalPort = 4242;
      destination = "192.168.2.31";
      destinationPort = 4242;
    }
  ];

  # Dynamic DNS Configuration (optional)
  dyndns = {
    enable = false;  # Set to true to enable dynamic DNS updates
    provider = "linode";  # Currently only "linode" is supported
    
    # Domain and record to update
    domain = "example.com";
    subdomain = "";  # Leave empty for root domain, or specify subdomain like "router"
    
    # Linode API credentials (stored in sops secrets)
    # domainId and recordId can be found using: linode-cli domains list / linode-cli domains records-list DOMAIN_ID
    domainId = 0;  # Your Linode domain ID
    recordId = 0;  # Your Linode DNS record ID
    
    # Update interval when WAN IP hasn't changed
    checkInterval = "5m";  # How often to check for IP changes
  };

  # Global DNS configuration
  dns = {
    enable = true;
    
    # Upstream DNS servers (shared by all networks)
    upstreamServers = [
      "1.1.1.1@853#cloudflare-dns.com"  # Cloudflare DNS over TLS
      "9.9.9.9@853#dns.quad9.net"        # Quad9 DNS over TLS
    ];
  };
}
